### PR TITLE
Adding more than 2 Files to 7z error

### PR DESCRIPTION
**Pull request by Lothrien**
Looking through RV code to find differences, doing some code cleanup, aligning code to find errors and adding some extra spaces #63

### CODE REVIEW

**Comment by Lothrien** [comment]
see we have 1 code from pull request before :(

**Comment by mnadareski** [comment]
Before I do a full review of this, is this just a flat copy-paste from RVWorld? Or did you manually make these changes? If so, I would strongly prefer the former and not the latter. I would rather be able to update directly from RomVault.

**Comment by mnadareski** [comment]
Also, the PR title doesn't actually fit the changes.

**Comment by Lothrien** [comment]
Yeah, but you have changed the variable names in your code. What I did is also sort some elements to what they are like in RV-World to better see differences in a code review software. Also you cleaned up more {} from the code. Some changes are also inspired by SharpCompress and should be used on RV-World code. SharpCompress only has the basic idea of 80 characters per line, which makes it unreadable sometimes.
The PR is from the error I got, basically the create 7z wasnt readable when you had more than 2 files in the 7z.

**Comment by mnadareski** [comment]
My code here is a 1:1 copy of a previous version of Compress. If anything syntactically changed, it should only be from that. If you're planning on doing a sync from RVWorld, please make it a 1:1 copy with no additional edits, if possible.

**Pull request closed without merging**
