### PR TITLE
Continue reading when nothing useful was found

### PR DESCRIPTION
**Pull request by Lothrien**

### CODE REVIEW

**Comment by mnadareski** [comment]
Can you provide examples of files that contain the section names that you're mentioning? I don't think you understand that the `[` and `]` are what determine what a section name is. Your change actually changes this to `[[roms]]`.

**Comment by Lothrien** [comment]
remember copying this from rv-world. i'll think there is an example test file for it also.

**Comment by mnadareski** [comment]
The title of this is a bit misleading. You're actually supporting new section names, not really dealing with continuing reading.

**Comment by Lothrien** [comment]
RVWorld-master\DATReader\DatReader\DatROMCenterReader.cs

**Comment by Lothrien** [comment]
ir.ReadNextLine(); is not performed, when nothing is found. so i added this to keep going. [] tags are from RVWorld (see above). Two things in one PR.

**Comment by mnadareski** [comment]
With regards to the linked class in RomVault, you may notice that our readers behave differently. I built an entirely separately INI-based file reader, which takes into account the `[` and `]` characters to ensure section names. Gordon's goes line by line and compares the full line.

With regards to the `ir.ReadNextLine()`, have you observed this getting stuck on a RomCenter DAT? The last time I tested this, it was functioning just fine, so I'm curious as to if something changed. If something _has_ broken, then I'll gladly take a fix for that part.

**Pull request closed without merging**
